export const names = [
    "C",
    "Python",
    "Java",
    "JavaScript",
    "C++",
    "C#",
    "Ruby",
    "Swift",
    "Go",
    "PHP",
    "HTML",
    "CSS",
    "Kotlin",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Statistical Analysis",
    "SQL",
    "Python (with libraries like pandas)",
    "R (with packages like dplyr)",
    "Excel",
    "Tableau",
    "Power BI",
    "MATLAB",
    "SAS",
    "Database Management",
    "SQ",
    "Machine Learning Algorithms",
    "Deep Learning Architecture",
    "Natural Language Processing (NLP)",
    "OpenCV",
    "TensorFlow",
    "PyTorch",
    "OpenAI Gym",
    "Stable Baselines",
    "RLlib",
    "Amazon Web Services (AWS)",
    "Microsoft Azure",
    "Google Cloud Platform (GCP)",
    "IBM Cloud",
    "Cloud Infrastructure",
    "Containerization",
    "Docker",
    "Kubernetes",
    "Serverless Computing",
    "AWS Lambda",
    "Azure Functions",
    "Network Security",
    "Network protocols",
    "Firewalls",
    "Intrusion detection systems (IDS) and Intrusion prevention systems (IPS)",
    "Virtual private networks (VPNs)",
    "Vulnerability Assessment",
    "Penetration Testing",
    "Incident Response",
    "Digital Forensics",
    "Project Planning and Scheduling",
    "Project Budgeting",
    "Cost Management",
    "Risk Management",
    "Project Documentation",
    "Project charters",
    "Stakeholder communication plans",
    "Change Management",
    "Project Closure and Evaluation",
    "Adobe Creative Suite (Adobe Photoshop, Illustrator, InDesign, etc.)",
    "Typography",
    "Layout Design",
    "Color Theory",
    "Visual brand identities",
    "Illustration",
    "Custom graphics",
    "Image Editing and Retouching",
    "Print Design",
    "User Interface (UI) Design",
    "Web Design",
    "Information Design",
    "Wireframing",
    "Interaction Design",
    "Prototyping",
    "Adobe XD",
    "Sketch",
    "Figma",
    "InVision",
    "Heatmaps: Microsoft Clarity, Hotjar, Crazy Egg",
    "Data Analysis",
    "Google Analytics",
    "Mixpanel",
    "Responsive Design",
    "Accessibility Design",
    "Financial Statement Analysis",
    "Financial Ratio Analysis",
    "Financial Modeling",
    "Valuation Techniques",
    "Risk Analysis",
    "Capital Budgeting",
    "Cost Analysis",
    "Financial Forecasting",
    "Investment Analysis",
    "Corporate Finance",
    "Financial modeling software",
    "Statistical analysis software",
    "Data visualization tools",
    "Amazon Web Services (AWS)",
    "Microsoft Azure",
    "Google Cloud Platform (GCP)",
    "IBM Cloud",
    "Cloud Infrastructure",
    "Containerization",
    "Docker",
    "Kubernetes",
    "Serverless Computing",
    "AWS Lambda",
    "Azure Functions",
    "Network Security",
    "Network protocols",
    "Firewalls",
    "Intrusion detection systems (IDS) and Intrusion prevention systems (IPS)",
    "Virtual private networks (VPNs)",
    "Vulnerability Assessment",
    "Penetration Testing",
    "Incident Response",
    "Digital Forensics",
    "Project Planning and Scheduling",
    "Project Budgeting",
    "Cost Management",
    "Risk Management",
    "Project Documentation",
    "Project charters",
    "Stakeholder communication plans",
    "Change Management",
    "Project Closure and Evaluation",
];
